### ISSUE TITLE
Label disappears if RGB setting is omitted in edges.csv

### ISSUE THREAD

**Issue by DiegoBneiNoah** [hackl/tikz-network#13]
I tried to omit the use of RGB in vertices.csv and edges.csv and I don't know if the label "C" was not shown to be related to this omission.

![image](https://user-images.githubusercontent.com/46031776/62090105-2ee46980-b25b-11e9-936d-c1d5440fc6f7.png)

My MWE following first page example 27 from manual tikz-network.

```
\documentclass{article}
\usepackage{tikz-network}
\thispagestyle{empty}
\begin{document}
\begin{tikzpicture}
\Vertices{data/vertices.csv}
\Edges{data/edges.csv}
\end{tikzpicture}
\end{document}

```
My new settings in edges.csv omitting RGB settings

```
u,v,label,lw,color ,opacity,bend
A,B, ab  ,.5,red   ,   1   ,  30
B,C, bc  ,.7,blue  ,   1   , -60
B,D, bd  ,.5,blue  ,  .5   , -60
A,E, ae  , 1,green ,   1   ,  75
C,E, ce  , 2,orange,   1   ,   0
A,A, aa  ,.3,black ,  .5   ,  75

```
My new settings in vertices.csv omitting RGB settings
```

id, x, y ,size, color,opacity,label,IdAsLabel,NoLabel
 A, 0,  0, .4 , green,  .9   ,  a  ,  false  , false
 B, 1, .7, .6 ,      ,  .5   ,  b  ,  false  , false
 C, 2,  1, .8 ,orange,  .3   ,  c  ,  false  , true
 D, 2,  0, .5 ,   red,  .7   ,  d  ,  true   , false
 E,.2,1.5, .5 ,  gray,       ,  e  ,  false  , false
```

**Comment by hackl** [comment]
Hi. This is not related to the RGB option. Instead please change the `NoLabel` option for `C` to `false` or remove the column `NoLabel`. If this option is enabled, the label of the node will be deleted (see Table 3.1. in the manual).

**Comment by DiegoBneiNoah** [comment]
I really thought it could be something like that but I didn't extend my reasoning, I did a test and it worked out fine. It was a big oversight. thankful @hackl .
