### ISSUE TITLE
shape C not found in the edges.csv 

### ISSUE THREAD

**Issue by DiegoBneiNoah** [hackl/tikz-network#14]
As pointed out at https://tex.stackexchange.com/questions/502182/shape-c-not-found-in-the-files-csv-tikz-network-package I ask your opinion @hackl and the suggestion for use of standalone in the manual examples in order to circumvent potential problems by users by compiling the same examples individually on their own. Thank you for writing this package which helps a lot to deal with and visualize the dynamics behind processes, especially with integrated information theory.

**Comment by hackl** [comment]
Thanks for pointing this out, I'll fix this bug as soon as possible.

**Comment by hackl** [comment]
This issue has been fixed (cc53a74). Now edges can be created without vertices as described in the manual in Section 4.2 Example 4.7. Furthermore, all examples used in the manual are available as standalone figures as suggested (4798d81).
