### ISSUE TITLE
Importing figures as layer pictures

### ISSUE THREAD

**Issue by Flobian** [hackl/tikz-network#2]
Could you please provide an example how to import figures as background images in the layers of a multilayer network, as used in the front page example network? Also, how do you create the labels next to the layers? 
If you just give the source code how to create the front image, that would be very helpful to see the necessary commands.

**Comment by hackl** [comment]
Hi,
I uploaded several small examples, including the multilayer network from the front page. I plan to upload more examples as time goes on.

For the grids and the background images of the figure in the manual, I used a function called `\Plane`:

`\Plane[layer=1,size=(10,10),grid=1cm,opacity=.6,image=field_a.pdf]`

which is currently not implemented in the library. Hence, I provided a workaround, which works but isn't so pretty. Please, also note that for the multilayer example you have to use `lualatex`.  There is also a workaround to use `pdflatex` and to speed up the compilation, by separating the edge file into separate files (i.e. `edges_11.csv`, `edges_22.csv`, `edges_12.csv`,...) and neglecting the options `layer={1,1}`, `layer={2,2}`, `layer={1,2}` ...

**Comment by Flobian** [comment]
Thank you, that helps a lot!
